name: Cron Workflow

on:
  schedule:
  - cron: '5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  cron:
    name: Cron Job
    runs-on: ubuntu-latest
    steps:
    - name: Echo Date
      run: |
        DATE_TIME=$(date)
        echo "Datetime: $DATE_TIME"
